sudo: false
language: python
python:
  - 2.7
  - 3.6
  - 3.7
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: 2.7
      env: DJANGO=2.1

before_install:
  - pip install django~=$DJANGO.0

script:
  - ./test_project/manage.py test -v 2  --with-coverage --cover-package=django_chunked_iterator

after_success:
  - coveralls
