sudo: false
dist: xenial
language: python
python:
  - 3.6
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
matrix:
  include:
    - python: 2.7
      env: DJANGO=1.11
    - python: 3.7
      env: DJANGO=2.1
      sudo: true

before_install:
  - pip install django~=$DJANGO.0

script:
  - ./test_project/manage.py test -v 2  --with-coverage --cover-package=django_chunked_iterator

after_success:
  - coveralls
